[package]
name = "heatmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.16", features = ["derive"] }
crossterm = "0.23.2"
polars = "0.21.1"
